baseURL = "https://awpremium.onrender.com"
canonifyURLs = true
description = ""
enableRobotsTXT = true
landscapePhotoWidths = [2500, 1500, 1000]
languageCode = "pl-PL"
portraitPhotoWidths = [1500, 1000, 750]
theme = "sc_aw_premium"
title = "AW premium"
[params]
description = ""
email_header = "kontakt@agencjawroclawska.pl"
favico = "/uploads/favicon-aw.png"
landscapePhotoWidths = [3400, 2560, 1920, 1600, 1366, 1200, 992, 786, 560]
paginatedsections = ["posts"]
portraitPhotoWidths = [1500, 1000, 750, 500]
[permalinks]
"/" = "/:06/:1/:2/:slug/"
premium = "/:slug/"
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
